--SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
--
--/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
--/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
--/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
--/*!40101 SET NAMES utf8mb4 */;
DROP TABLE IF EXISTS texts;

CREATE TABLE `texts` (
  `id` int(11) NOT NULL PRIMARY KEY,
  `text2check` text DEFAULT NULL,
  `span` text DEFAULT NULL,
  `info` text DEFAULT NULL,
  `alternative1` text DEFAULT NULL,
  `text1` text DEFAULT NULL,
  `count1` int(11) DEFAULT 0,
  `alternative2` text DEFAULT NULL,
  `text2` text DEFAULT NULL,
  `count2` int(11) DEFAULT 0,
  `alternative3` text DEFAULT NULL,
  `text3` text DEFAULT NULL,
  `count3` int(11) DEFAULT 0,
  `alternative4` text DEFAULT NULL,
  `text4` text DEFAULT NULL,
  `count4` int(11) DEFAULT 0,
  `manual_rewrite` text NOT NULL DEFAULT '0'
);

INSERT INTO `texts` (`id`, `text2check`, `span`, `info`, `alternative1`, `text1`, `count1`, `alternative2`, `text2`, `count2`, `alternative3`, `text3`, `count3`, `alternative4`, `text4`, `count4`, `manual_rewrite`) VALUES
(1, 'È possibile partecipare a open-day con visite guidate, seminari e lezioni aperte, incontri con professionisti e tutor universitari. ', 'professionisti; tutor universitari', 'Using the masculine for the whole group is asymmetrical: in Italian, the presence of a single man is sufficient for having to use the masculine but the presence of neither one nor many women is sufficiente for having to use the feminine. It does not have to be so, though: you can use different formulations, such as the one proposed below.', 'professioniste/i; tutor universitari/e', 'È possibile partecipare a open-day con visite guidate, seminari e lezioni aperte, incontri con professioniste/i e tutor universitari/e. ', 0, 'esponenti del mondo del lavoro; tutor dell`università', 'È possibile partecipare a open-day con visite guidate, seminari e lezioni aperte, incontri con esponenti del mondo del lavoro e tutor dell`università.', 0, 'professionistɜ; tutor universitariɜ', 'È possibile partecipare a open-day con visite guidate, seminari e lezioni aperte, incontri con professionist* e tutor universitari*. ', 0, 'professioniste/i/ɜ; tutor universitari/e/ɜ', 'È possibile partecipare a open-day con visite guidate, seminari e lezioni aperte, incontri con professionist*/e/i e tutor universitari/e/*. ', 0, '0'),
(2, 'Inoltre, gli iscritti possono usufruire anche del servizio di tutorato che aiuta nel percorso formativo.', 'gli iscritti', 'Using the masculine for a mixed-gender group amounts to depict women as an exception, regardless of whether you want to or not: "If you have a group half of whose members are A`s and half of whose members are B`s and if you call the group C, then A`s and B`s may be equal members of group C. But if you call the group A, there is no way that B`s can be equal to A`s within it. The A`s will always be the rule and B`s will always be the exception—the subgroup, the subspecies, the outsiders." Alma Graham (1974)', 'gli iscritti e le iscritte', 'Inoltre, gli iscritti e le iscritte possono usufruire anche del servizio di tutorato che aiuta nel percorso formativo.', 0, 'coloro che si iscrivono', 'Inoltre, coloro che si iscrivono possono usufruire anche del servizio di tutorato che aiuta nel percorso formativo.', 0, 'lɜ iscrittɜ', 'Inoltre, lɜ iscrittɜ possono usufruire anche del servizio di tutorato che aiuta nel percorso formativo.', 0, 'gli iscritti, le iscritte e lɜ iscrittɜ', 'Inoltre, gli iscritti, le iscritte e lɜ iscrittɜ possono usufruire anche del servizio di tutorato che aiuta nel percorso formativo.', 0, '0'),
(3, 'Il diplomato che intenda immatricolarsi a uno dei corsi di laurea offerti dal Dipartimento deve sostenere una prova di ammissione, nella forma di test obbligatorio a carattere orientativo.', 'Il diplomato', 'Have you ever thought that a woman or a non-binary person might not recognize themselves in an expression such as "Il diplomato"? If you want to avoid it, you could substitute "Il diplomato" with one of the proposed alternatives, specifically designed not to make anyone feel excluded.', 'Il diplomato o la diplomata', 'Il diplomato o la diplomata che intenda immatricolarsi a uno dei corsi di laurea offerti dal Dipartimento deve sostenere una prova di ammissione, nella forma di test obbligatorio a carattere orientativo.', 0, 'Chi', 'Chi intende immatricolarsi a uno dei corsi di laurea offerti dal Dipartimento deve sostenere una prova di ammissione, nella forma di test obbligatorio a carattere orientativo.', 0, 'Lǝ diplomatǝ', 'Lǝ diplomatǝ che intenda immatricolarsi a uno dei corsi di laurea offerti dal Dipartimento deve sostenere una prova di ammissione, nella forma di test obbligatorio a carattere orientativo.', 0, 'Il diplomato, la diplomata o lǝ diplomatǝ', 'Il diplomato, la diplomata o lǝ diplomatǝ che intenda immatricolarsi a uno dei corsi di laurea offerti dal Dipartimento deve sostenere una prova di ammissione, nella forma di test obbligatorio a carattere orientativo.', 0, '0'),
(4, 'Il test comprende quesiti di logica, di comprensione verbale e di matematica a cui si aggiungono quesiti di valutazione della conoscenza della lingua inglese.', '', 'This text is perfect as it is: hurray!', '', '', 0, '', '', 0, '', '', 0, '', '', 0, '0'),
(5, 'Ai fini test si considera superato se si ottiene un punteggio maggiore o uguale alla soglia fissata dai regolamenti didattici.', '', 'This text is perfect as it is: hurray!', '', '', 0, '', '', 0, '', '', 0, '', '', 0, '0'),
(6, 'Un risultato che evidenzi lacune attribuisce Obblighi formativi aggiuntivi (OFA).', '', 'This text is perfect as it is: hurray!', '', '', 0, '', '', 0, '', '', 0, '', '', 0, '0'),
(7, 'Tutti coloro ai quali sono stati attribuiti tali obblighi hanno a disposizione economia, accessibile a chiunque in maniera libera e gratuita.', 'Tutti coloro ai quali', 'Using the masculine for the whole group obscures the presence of women and non-binary people. To avoid make them invisible, substitute "Tutti coloro ai quali" with one of the proposed alternatives or add one you like in the box.', 'Tutte e tutti coloro a cui', 'Tutte e tutti coloro a cui sono stati attribuiti tali obblighi hanno a disposizione economia, accessibile a chiunque in maniera libera e gratuita.', 0, 'Coloro a cui', 'Coloro cui sono stati attribuiti tali obblighi hanno a disposizione economia, accessibile a chiunque in maniera libera e gratuita.', 0, 'Tuttɜ coloro a cui', 'Tuttɜ coloro a cui sono stati attribuiti tali obblighi hanno a disposizione economia, accessibile a chiunque in maniera libera e gratuita.', 0, 'Tutte, tutti e tuttɜ coloro a cui', 'Tutte, tutti e tuttɜ coloro a cui sono stati attribuiti tali obblighi hanno a disposizione economia, accessibile a chiunque in maniera libera e gratuita.', 0, '0'),
(8, 'Per assolvere il suddetto OFA, il candidato deve superare un test di verifica finale che viene organizzato in più sessioni funzionali al calendario degli esami.', 'il candidato', 'Have you ever thought that a woman or a non-binary person might not recognize themselves in an expression such as "il candidato"? As this study shows, using the masculine might $ https://www.researchgate.net/publication/328707830_Kick-Starting_Female_Careers_Attracting_Women_to_Entrepreneurship_Programs $ discourage a woman $ to apply for a job', 'il candidato o la candidata', 'Per assolvere il suddetto OFA, il candidato o la candidata deve superare un test di verifica finale che viene organizzato in più sessioni funzionali al calendario degli esami.', 0, 'bisognerà', 'Per assolvere il suddetto OFA, bisognerà superare un test di verifica finale che viene organizzato in più sessioni funzionali al calendario degli esami.', 0, 'lǝ candidatǝ', 'Per assolvere il suddetto OFA, lǝ candidatǝ deve superare un test di verifica finale che viene organizzato in più sessioni funzionali al calendario degli esami.', 0, 'il candidato, la candidata o lǝ candidatǝ', 'Per assolvere il suddetto OFA, il candidato, la candidata o lǝ candidatǝ deve superare un test di verifica finale che viene organizzato in più sessioni funzionali al calendario degli esami.', 0, '0'),
(9, 'In caso di mancato recupero degli OFA di matematica, bisognerà concordare le modalità di recupero con il docente di riferimento.', 'il docente', 'What if the teacher is a woman? Or a non-binary person? Several studies show that using the masculine evokes images of men and makes it more difficult to realize that it could be a woman or a non-binary person (see $ https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2016.00025/full $ Sczesny et al 2016 $ )', 'il o la docente', 'In caso di mancato recupero degli OFA di matematica, bisognerà concordare le modalità di recupero con il docente di riferimento.', 0, 'il personale docente', 'In caso di mancato recupero degli OFA di matematica, bisognerà concordare le modalità di recupero con il personale docente di riferimento.', 0, 'lǝ docente', 'In caso di mancato recupero degli OFA di matematica, bisognerà concordare le modalità di recupero con lǝ docente di riferimento.', 0, 'il, la o lǝ docente', 'In caso di mancato recupero degli OFA di matematica, bisognerà concordare le modalità di recupero con il, la o lǝ docente di riferimento.', 0, '0'),
(10, 'I regolamenti didattici dei corsi di laurea magistrale definiscono i requisiti curriculari minimi e di personale preparazione', '', 'This text does not contain any gende-unfair expressions and, thus, does not need any change: fantastic!', '', '', 0, '', '', 0, '', '', 0, '', '', 0, '0');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
